key-labels.a = "Key A"
key-pins.a = 1

key-labels.b = "Key B"
key-pins.b = 2

song-labels.a = "Song A"
song-paths.a = "/path/to/song-a.wav"

song-labels.b = "Song B"
song-paths.b = "/path/to/song-b.wav"

song-labels.neither = "Neither song"
